name: Build and Deploy Gatsby Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Cache NPM Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install --force

      - name: Install gh-pages
        run: npm install -g gh-pages

      - name: Configure Git
        run: |
          git config --global user.email "ssol0319@naver.com"
          git config --global user.name "Cyma-s"
      
      - name: Build and Deploy
        run: |
          npm run build
          GH_TOKEN=${{ secrets.GITHUB_TOKEN }} gh-pages -d public -b deploy
