name: Build and Deploy Gatsby Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install --force

      - name: Install gh-pages
        run: npm install -g gh-pages

      - name: Build and Deploy
        run: npm run build && gh-pages -d public -b deploy
